[workspace]
channels = ["conda-forge"]
name = "siRNADiscovery_env"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.1"

[system-requirements]
cuda = "12"

[tasks]
train-siRNA = { cmd = "python siRNADiscovery.py", cwd = "siRNA_split/" }
train-mRNA = { cmd = "python siRNADiscovery.py", cwd = "mRNA_split/" }
predict-siRNA = { cmd = "python predict.py --model-weights $MODEL_WEIGHTS --sirna-seq $SIRNA_SEQ --mrna-seq $MRNA_SEQ", cwd = "siRNA_split/" }
predict-mRNA = { cmd = "python predict.py --model-weights $MODEL_WEIGHTS --sirna-seq $SIRNA_SEQ --mrna-seq $MRNA_SEQ", cwd = "mRNA_split/" }
predict-siRNA-csv = { cmd = "python predict.py --model-weights $MODEL_WEIGHTS --csv $CSV --output $OUTPUT", cwd = "siRNA_split/", env = {OUTPUT = "predictions.csv"} }
predict-mRNA-csv = { cmd = "python predict.py --model-weights $MODEL_WEIGHTS --csv $CSV --output $OUTPUT", cwd = "mRNA_split/", env = {OUTPUT = "predictions.csv"} }

[dependencies]
python = "3.11.*"
pandas = "*"
numpy = "*"
scikit-learn = "*"
scipy = "*"
biopython = ">=1.81"
matplotlib = ">=3.7"

[target.linux-64.dependencies]
tensorflow = { version = "2.15.*", channel = "conda-forge" }
cudnn = "*"

[target.osx-arm64.dependencies]
pip = "*"

[pypi-dependencies]
stellargraph = "*"
chardet = "*"

[target.osx-arm64.pypi-dependencies]
tensorflow = ">=2.15.0,<2.16"
tensorflow-metal = "*"
